import PrivateRoutes from "./PrivateRoutes/PrivateRoutes";
import Header from "./Header/Header";
import Footer from "./Footer/Footer";
import NewsLatter from "./NewsLatter/NewsLatter";
import Slider from "./Slider/Slider";
import LoginForm from "./UserAuthComponents/LoginForm";
import SignUpForm from "./UserAuthComponents/SignUpForm";
import PostForm from "./PostForm/PostForm";
import DashBoardAsideBar from "./DahBoardComponenets/DashBoardAsideBar";
import DeshBordHeader from "./DahBoardComponenets/DeshBordHeader";
import AdminPostShow from "./DahBoardComponenets/AdminPostShow";
import AllPosts from "./AllPosts/AllPosts";
import DetailPostCard from "./DetailPostComponents/DetailPostCard";
import HomePostSection from "./HomePostSection/HomePostSection";
export { PrivateRoutes, Header, Footer, NewsLatter, Slider,LoginForm ,SignUpForm,PostForm , DashBoardAsideBar,DeshBordHeader,AdminPostShow,AllPosts,DetailPostCard,HomePostSection};